### ISSUE TITLE
Hello Repository Author pegasus1982.

### ISSUE THREAD

**Issue by computerfever** [pegasus1982/fabricjs-image-editor-origin#4]
Can I use this code in my project?.
Please Reply.

**Comment by pegasus1982** [comment]
Sure, you can use my code anywhere.

**Comment by sajov** [comment]
@pegasus1982 i like your work a lot!
Is there any chance to get in contact for freelancing or more?

**Comment by pegasus1982** [comment]
@sajov Please let me know your email, I will DM you.

**Comment by sajov** [comment]
Hi @pegasus1982 you can contact me at sascha.jovanoski@gmail.com

**Comment by BenjaminIrwin** [comment]
@pegasus1982 amazing work! Thank you. Can I use the repo in project? (Checking since there is no license)

**Comment by pegasus1982** [comment]
@BenjaminIrwin 
You can use my repo without any limitation!
Would you please give a star instead?

**Comment by BenjaminIrwin** [comment]
Thank you legend. Have given you the star!
