### ISSUE TITLE
Can you contact me about customizing the editor?

### ISSUE THREAD

**Issue by vandijkict** [pegasus1982/fabricjs-image-editor-origin#6]
Hi can you contact me about customizing your editor as a freelance job?

you can contact me by email: erik@vandijkict.nl

Kind regards,

Erik

**Comment by pegasus1982** [comment]
Sent.
Thank you for your interesting.

**Comment by vandijkict** [comment]
Hi,

Thanks for your reply,
We have customer with a web2print website.
They want to give customers the option to create their designs online with an online editor.

We checked your editor, and it works great and minimalistic.

What are the options for customizing?
For example, a customer chooses a product like a banner of flag with a specific size.
Then we want to start the editor with the canvas size of their chosen product.

After editing we want to save the design on our server and maybe let them edit it later again.

Is that possible?

Met vriendelijk groet,

Erik van Dijk

[LogoMail]

[Icon1]
WEEGBREE 13

7742 TC COEVORDEN
[Icon2]
+31 (0)6 28 27 58 33
[Icon3]
***@***.*** ***@***.***>
[Icon4]
WWW.VANDIJKICT.NL <http://www.vandijkict.nl/>


Van: J.S ***@***.***>
Verzonden: vrijdag 5 mei 2023 14:41
Aan: pegasus1982/fabricjs-image-editor-origin ***@***.***>
CC: Erik van Dijk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pegasus1982/fabricjs-image-editor-origin] Can you contact me about customizing the editor? (Issue #6)


Sent.
Thank you for your interesting.
